server:
    port: 8092
    tomcat:
        max-connections: 20
        threads:
            max: 20
            min-spare: 10
            accept-count: 10

# 微信公众号对接
weixin:
    config:
        originalid: gh_026279ec86bd
        token: b8b6
        app-id: wx6d57f6c50c5b186b
        app-secret: f6360ce33e3a7797c64a5f0a3f1039fd
        template_id: zH-GSu1Q4WHXfgIqBmkzh7qZZJPbP42JOy93XNvl2sM

spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:13306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat

mybatis:
    mapper-locations: classpath:/mybatis/mapper/*.xml
    config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://openhome.alipay.com/develop/sandbox/app
alipay:
    enabled: true
    app_id: 9021000168647635
    merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCbhDdYnDUQXM+qaQGKYrstBhYd92U4ajazlZvg1oqhlMJE2bjtBv0lj38vX1CKNZ9WdY6Pl9Tmu1PgqnxGGrn0A6fMoJplzAcUp0qcvFPbH6xvr7qu2SZao6VaKchoJi0ETcJc+NpetDO3byZMGQkNlEHjMbIIMq8jKS/kZ2fyTVKJg9/CanEoUiArA37ndyu/fP43NFnvKnH4Z0zO7XMbmMApj4K2qngpu9jCkhnhXdCsIHd9YKCdyLh0KWC+QD/R8WaYHpVpTJxXMT1XynK47OhvDvXGOQFuaH91h8rJGrlkJztpMpoQQrdXdeoc3olJ9jLrgeseVrM3PKUpCN+VAgMBAAECggEBAInV59ALsyRrfkuFgi4LT+aZ7GRm7znPOeh1g5EF1h1cYcrwRe0fMqNlyc5M5m95E15oFxDB+5r9EVyg/kCMU6Ao1UKSXgY3jVcK5yB/8rrWGdlroURzhoDzZgzB17QnkeKsoMYScklZ4jSEuSbdUZ7NdpBNbYPCmGPLj30bAZBJAitHEK22h4OBTntg8LwoWOQzmYJ3EswsJen+ewYfPEtwWOS1wve6SIKaMOvRWWB180Xdrn/jnp+nuv4XabjlZm5nH99e4Hw/uDzprL7CRfXcVR/zOMN+tqwm9h+OquKpameWFKMwN3TLxm46Z0n/pP79gpAyO9DyOyOo/KVlsQECgYEAzhOEeEf9CO5WOIwooEaSSRMocLCF6+SFwzw1olhXL1YEbRrcV0/pzjB0FEjXdtYwTSi3LkhPMmc8/ch24ct94IqNMLmHSzpqzEFDAKydusWahwd1ZPIb2wWY2I/EwPPoYkcmdx8lgeuFUI5R0NOw0XAOJOa77IpjopbL2LQEruECgYEAwTEST8FDqjz+tTUQ0GEgBrabGMBIGvoV4NGPBBPoRe2qPGG/U4A4lZu6keFQ6QpjL72wS0oXFlFia+erX+S0OBKhNKaiFFJMQ3uG8PD0aINyWK1UeXMGNsPtrEfodD6d7zQPRAGKB0bhwYf4u8VYNWTAIIEE8ppE7w1+RlMtCzUCgYEAvmnyYWHDQNlY+e8oKtCKotL87wNs+0axAnFD7bpK9QY6GMZVCqhglZDX8VZNIRVQlDsm57EQ3LXf+W+dyY1Jxoy/YWJMzQoxXIKA8sKNC+NCoboWkyvS6VIGpTRSzSeSdhzgQfmZoq6JBKI8nwS7wQoVR6ubwTkuTzGfMaFFIoECgYA3zukvSPE3GG+sASxeRfBugAnF2KX7xQrU6zSZRPbwXHu0/be7c2rlLRt0UNaCu5FzlSR8W2bX96Kq8T28ceDt4dPX1ds0a6HETMbqi3DPUEmT/F5Oxz+gSnE6N3ubOQt+sldGmfs5puxIb/MWqyeUJQqrWRoIyy/mrssvnY+BkQKBgEkREgUdIoodjjWgmN5WQ8GKh/Fuy+J6u02FZxOg4sAfG9i0+Ia6BCsc2F9uLAEGciPkJUp6HOcVX89riMT+w1Pflkeh4dIYOEihw++VkiDrTGS6oJPmzJ1s4MDQmfTNEuB3YHCAuWRLrYb44xenhnzU1mbzF4yoGneSzJeao3ho
    alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyhDPW/spysqptOLv5IYYOE/6SmW/rQYBz8yP17vr4vxFRsazrUpmZICV6/Fxpgu64jsEEVmn6IbvC8m3YgsgYtzBOnFYeWEFiSTbFzA7777OOVgOgwmnoUJchpvgzsJQIiVveE2oTj7Xe1+F9mLbrOqAWHVGraFUDIs1iljP8tvY011RF2ZL+GATiCbTp3HByd0VAAlCHKMl/8IEUXuw3Kju0FjcFfI4yLFicjGpeCdE6IsCe0gHS9+LGtY5M3Xq72mCC9b2jOkwu2kVZdMNUIlW5Vv0xewtmbsRxqzPBGhMPEWC33c1gd5ZtVSW+YmPChBtP1+9+iLUxO24iD8GJQIDAQAB
    notify_url: https://225b91df.r15.vip.cpolar.cn/api/v1/alipay/alipay_notify_url
    return_url: https://gaga.plus
    gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do


# 日志
logging:
    level:
        root: info
    config: classpath:logback-spring.xml